### ISSUE TITLE
Consulta sobre la corrección del paquete.

### ISSUE THREAD

**Issue by MatiFasolato** [MatiFasolato/meteorodata#7]
Buenos días/tardes. Con Bautista nos pusimos a trabajar para corregir los errores indicados en la corrección del paquete. Nos surge la duda sobre a qué hace referencia la observación de "No encontramos un archivo que prepare los datos". Gracias y perdón por la molestia!
@paocorrales
@yabellini

**Comment by paocorrales** [comment]
Hola Matias, no es ninguna molestia! 

Con eso nos referimos a un archivo .R (normalmente en la carpeta data_raw) que lee/organiza/manipula los datos y luego corre `usethis::use_data()`. Si bien este archivo no entra en el paquete construido, es una buena práctica incluirlo en el repositorio para que quede el registro/receta de donde salieron los datos. 

En la parte 1 del parcial tienen un ejemplo (que tuvieron que completar) y [acá hay otro con el paqueteprueba](https://github.com/paocorrales/paqueteprueba/blob/master/data_raw/crea_datos.R).

Espero que sirva!

**Comment by MatiFasolato** [comment]
Perfecto profe, ahora nos ponemos con eso entonces. Gracias!
